### ISSUE TITLE
There is an ES6 version , why do we need a TypeScript  version?

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi-typescript#107]
TypeScript is very like ES6 , why do we need a TypeScript  version?

**Comment by clark-stevenson** [comment]
Personal choice. Working with TypeScript is sweet.  Since your code is typed, the code knows it's context and so tooling is far better,  especially on multi person, or large code bases. It reduces errors considerably and alleviates you from many otherwise dull chores.  Having just worked with a traditional JS lib at work this week, I want to cry.  :(

**Comment by ivanpopelyshev** [comment]
Because Typescript is better? At least its modularity.

**Comment by clark-stevenson** [comment]
A great example. 

```
function addTwoNumber(number1, number2){
```

They know their Intent,  in JavaScript, intent is lost by definition.  This is valid at the time of author

`let value = addTwoNumbers("string", new Date())`

You may laugh at my noob, but how was I supposed to know? The only person that knows that, is English Speakers, You, the Docs which end up in 150 PRs and the Unicorns (does it return or adjust in its content in his context?). 

When the original JS dude wrote this function, he automatically knew his intent.  By throwing away his intent (a language shortcoming), he had to repeat himself with docs, maintain those docs, and force me, as a user, to consult these docs.  

```
addTwoNumber(number1: number, number2: number): number {
}
```

Can you please share that data with me??? If I am using this API, that is 100% useful to know.  No less than 100% and never will be a lower figure than 100%. 

If someone can shed a light on why they would choose ES6 over TypeScript, in a real world non-academic setting as an employee or an owner of a company. I am desperate to be educated because so far, no one, since 2011 outside of academia, has adequately provided a counter to this argument. 

So no other benefits matter.  All other benefits, are just bonuses, and there are many.

**Comment by ivanpopelyshev** [comment]
@clark-stevenson because they're hipsters and I'm java guy :)
