### ISSUE TITLE
npm @types/pixijs

### ISSUE THREAD

**Issue by lilumat** [pixijs/pixi-typescript#121]
Hello,
Have you planned to merge in https://github.com/DefinitelyTyped/DefinitelyTyped/tree/types-2.0/pixi.js because when you do **npm @types/pixijs**, it's always the version 3.0
Best regards

**Comment by ivanpopelyshev** [comment]
There's an active PR for pixi and pixi-spine: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/12648

**Comment by bluepichu** [comment]
Is there a good way to keep these in-sync long term?  Because now @types is out-of-date again (on 4.1.0 when the current version is 4.3.0).

**Comment by clark-stevenson** [comment]
I am hoping some day soon to see about adding this to the official repo so that the types travel with the project.   The @types thing isn't working too well for me at all (another failed PR open on DT for 4.3.0 as we speak).

However, I am struggling with the next step. I need to split `pixi-gl-core` into `/pixi-gl-core/src/index.d.ts` so that it travels with the project via the `package.json` right?

After extracting this from the definitions, we have a bunch of errors, because the core has been extracted and externalized. 

Now if we go over to `pixi.js` official. I am wanting to make a PR with the remaining file from here,  but, how do I deal with the dependency of `pixi-gl-core` which is needed for my `pixi.js/src/index.d.ts` for example?  Does it mean that if pixi.js bumped `pixi-gl-core`, my dependency issues would go away?

It is not just this core.  It is all of the other dependencies like EventEmitter.... What if EventEmitter doesn't have types? What if I used @types/EventEmitter but tomorrow EventEmitter had its own types like I want to do here?

I don't really know how to put all of this stuff together with any confidence that it works.

**Comment by clark-stevenson** [comment]
Thanks to @ivanpopelyshev @bluepichu @andy-ms  then we are good to go on 

`npm install @types/pixi.js`  

With all the files in place, and merging issues fixed, I will always attempt to periodically update @types either periodically with fixes reported by the community, or when a new version is released. 

I will add this to the readme soon.  Thanks for your help everyone!
