### ISSUE TITLE
Add Mapped Types or make everything public?

### ISSUE THREAD

**Issue by clark-stevenson** [pixijs/pixi-typescript#132]
[Discussion here](https://github.com/pixijs/pixi-typescript/pull/131)

**Comment by ivanpopelyshev** [comment]
YES

**Comment by giraluna** [comment]
I didn't completely understand the issue in the last thread, but @ivanpopelyshev is absolutely right in that many of Pixi's `private` and `protected` bits are actually `internal`; forbidden from users but required to be accessible by rendering code etc. The problem is, Typescript doesn't have an `internal` keyword. And [even if it did](https://github.com/Microsoft/TypeScript/issues/5228), we probably couldn't use it in writing declaration files.


It also doesn't seem like mapped types can be used for exposing properties. `keyof` only returns properties that are public to begin with.

> [For any type T, keyof T is the union of known, public property names of T.](https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Advanced%20Types.md#index-types)


I think the two options this leaves us with are:
- Dynamic property access `texture["_uvs"]`. [The intended way for bypassing accessibility modifiers.](https://github.com/Microsoft/TypeScript/issues/12111#issuecomment-259568490)
- Having a secondary declaration file where everything is public. Allows the prettier `texture._uvs` syntax. This should 100% be generated from the primary definitions.

**Comment by clark-stevenson** [comment]
Thanks for your input giraluna, really helpful! 👍 

I have been thinking about this for a few hours, and I don't really like either solution lol.

1. I don't want to mess up the API so that everything has tons of `_` for intellisense (but as long as it is valid, then it IS valid in real life).
1. I don't want to end up with a build step, or some selection of definitions where you can pick and choose, as it is just a hassle later. 

I need to find out a 2016 answer to "Do private and protected belong in a Definition".  

The design of the system is saying yes,  the technology we are trying to model is saying no.  Ultimately if the technology allows you to do something, we shouldn't be putting up a wall on the TypeScript side, preventing anyone from using it, as they would use the JavaScript version.  In other words, everything is and always will be public.

**Comment by clark-stevenson** [comment]
So I don't like it and never did it!

There is generally a rule (from manual definitions back when this was new) where only the public interface is exposed.  I followed that rule until one day, I was using Phaser a few years ago, and I had called a private variable of mine, something which was a private variable of Phaser's Object that I was extending. That was intense, it took days to find the bug. (My overriding of _start for example which wasn't flagged via the public interface)

So hence protected.  This was a "mid ground" between never experiencing that bug while maintaining the public usage interface. 

General usage of the definition by the majority would be filled with `this._` intellisense and I don't like it.  It is ugly and serves only the top 2%.  

Since it is unlikely I will invest the time in making multiple versions via some tool, then the options are:

1. Put you head on the chopping block and Find replace `protected` with nothing and make the PR so I can send future hate mail to you. 
1. Use any other work arounds provided above or do the magical cast to `any`.  

Ultimately what is needed is a TypeScript implementation, and trying to access `private _blah` or `protected _blah` may be unacceptable from our perspective, yet, it isn't public.  It is private for a reason, the author made it private, intending you shouldn't go there, don't access it... it is closed, off bounds... forget about it. 

The fact you can bypass his wishes doesn't belong in TypeScript or in the wider architecture of anything that is stable. 

I await the PR (and to be schooled) 😄
