### ISSUE TITLE
Namespace 'PIXI' has no exported member 'IRendererOptions'.

### ISSUE THREAD

**Issue by hevarnl** [pixijs/pixi-typescript#150]
Since the #149 commit I get some errors in our project.

`browserify precompile: node_modules/@types/pixi.js/index.d.ts(23,82): Error TS2694: Namespace 'PIXI' has no exported member 'IRendererOptions'.
`

To temporary solve the issue I had to downgrade pixi and pixi-typescript to v 4.3.1.

**Comment by clark-stevenson** [comment]
Sorry for the delay on this!

What was awkward is that I couldn't reproduce. 

If I add the following to inside some function or URL inside `pixi.js-tests.ts` then I get no compilation or compile errors. 

```
            const options: PIXI.IRendererOptions = {
                clearBeforeRender: true
            };
```

It may be a related problem with DefinitelyTyped,  it usually takes 2-3 generations of family members to successfully merge a PR.  I will chase this up again this week and hopefully it will resolve your problem so that you get the latest version with `@types`

**Comment by clark-stevenson** [comment]
Closing as Stale and cannot reproduce.  Feel free to re-open with additional details if the problem continues.
