### ISSUE TITLE
PIXI.sound typings?

### ISSUE THREAD

**Issue by dakom** [pixijs/pixi-typescript#155]
I'm new to typescript... have all the main PIXI.js stuff working with webpack etc. but PIXI.sound isn't turning up. What's the process look like for getting that working?

**Comment by bigtimebuddy** [comment]
I believe the reason for this is because the typings in `PIXI.sound` are module typings not global typings. In other words, they do not export on a namespace, so you need to import explicitly to get a reference to the APIs: `import sound from 'pixi-sound'; sound.Sound.from('blah', 'blah.mp3');`

**Comment by dakom** [comment]
Cool, thanks for the insight. Closing it though no doubt it speaks to a larger meta issue of folding the various PIXI sub-projects under one umbrella.

**Comment by bigtimebuddy** [comment]
No problem. I will add an issue for myself on PIXI.sound to have optional global typings, in case someone wants to use those instead. I did something similar on [pixi-animate](https://github.com/jiborobot/pixi-animate).

**Comment by clark-stevenson** [comment]
Thanks guys. 

Yeah this repo definitely has a problem which has bothered me for a long time.  I want the acquisition process to be invisible.  This was something pushed by Matt over a year ago.  

However, ideally it would be automated, but at the end of the day, after having various stabs at this over the months, results have been wrong or `any`.   There is also a deeper problem of dependencies, `pixi-gl-core` needs out of this and into something like `pixi-gl-core/index.d.ts` and pointed out in the package.json   of that project. Whereas this seems a simple task, I am reluctant  to start pushing stuff into the official projects because ultimately I don't know what I am doing and since automation has remained unsolved, I feel these don't quite belong as part of the official library.  A bit manual and dirty compared to the quality of the official project. 
 
I still always try to find solutions though and enjoy seeing attempts.  This was informative. https://github.com/material-components/material-components-web/issues/134

I also see Microsoft is really making an effort on the tools, I think even relaxing the Type system for JavaScript developers.  I am sure something we can use will come along soon to aid this problem for larger libraries.  (It is almost like they are becoming a kind of Flow-like inference)
