### ISSUE TITLE
is it better to add document comment to index.d.ts ?

### ISSUE THREAD

**Issue by loohoo** [pixijs/pixi-typescript#202]
we need check document for some api when coding. 
![xxx7](https://user-images.githubusercontent.com/7367421/47506739-4b560e80-d8a3-11e8-8cdd-7c9f4f379046.png)

not so much usefull.

**Comment by ivanpopelyshev** [comment]
This thing is manual, not automatic. Its general problem of many typescript projects. We need a tool that combines `d.ts` and original jsdoc.

**Comment by clark-stevenson** [comment]
@loohoo 

I completely agree, but as Ivan said this is a manual process, and to make it worse, `@types/pixi.js` is differently formatted.  

With v4 `@types` well used in the world and v5 around the corner.  I will not support docs since it becomes a third layer of inconsistency.   It is unfortunate that you must seek documentation, but forward this to the pixi project and vote for TypeScript.

**Documentation will not be supported on v4**
