### ISSUE TITLE
Container .on typings

### ISSUE THREAD

**Issue by julien-moreau** [pixijs/pixi-typescript#207]
Hey wassup ? :)

My team and I noticed that the .on and .off methods signatures on a Container are not following the .on and .off signatures of DisplayObject

So the intellisense for a Container just offers "added" and "removed" :(
The DisplayObject allows all "interaction.InteractionEventTypes" so it's really cool =D

Is there a reason that Container doesn't follow the DisplayObject signatures for events ?
What we see:
`event: interaction.InteractionEventTypes | "added" | "removed"`

Do you agree ? I can PR if needed :)

Thnaks!

**Comment by clark-stevenson** [comment]
Hey @julien-moreau  👍 

Hmmm good question!  Since `Container extends DisplayObject` I would have expected that it would contain all of those events but that is really hazy for me to remember.

It has been a while since I used Pixi though.  If you are in a position to try it and make a PR, I would appreciate it a lot. 

I will wait for that before I make a `4.8.3` tag and push it to definitely typed.  💃

**Comment by clark-stevenson** [comment]
Thanks @julien-moreau  👍 

I PR to definitelytyped as well so should be there soon. 

Appreciated
