### ISSUE TITLE
Provide a basic example?

### ISSUE THREAD

**Issue by alamboley** [pixijs/pixi-typescript#213]
Hey moving from Haxe to TypeScript, could you provide a very basic example? Those on pixi-haxe helped a lot to get started!

**Comment by ivanpopelyshev** [comment]
Here, many examples:

https://github.com/pixijs/pixi-typescript/blob/v4.x/pixi.js-tests.ts

Also pixi-v5 uses its own typings, so if you move to v5, you dont need this repo.

**Comment by ivanpopelyshev** [comment]
Examples were made by converting pixi-examples.

**Comment by ivanpopelyshev** [comment]
Oh wait, you need examples of how to build it, right? Do you know how "tsconfig.json" works? I can help you only if you know how do you want to build TS app in general.

There are some TS builds here: https://github.com/pixijs/pixi.js/wiki/Boilerplate , but I dont use them, I just use simple TS concatenation, the same way haxe works.

**Comment by alamboley** [comment]
Thanks for the quick answer @ivanpopelyshev. Indeed I've to learn more in details how "tsconfig.json" works. I was looking for something similar to https://github.com/pixijs/pixi-haxe/blob/dev/build.hxml building examples and having everything ready (html/lib/images) etc.

**Comment by ivanpopelyshev** [comment]
yeah, that's the problem. We dont have that kind of examples, and even I create it from scratch every time by copying tsconfig from my other projects. I cant give you that, because i believe it will only make you stuck, you have to be aware of how things work there. Google "tsconfig", learn how to add your own libRoots there, and how to add extra "d.ts" files in a project.

I can only give a few pointers.

Alternatively, go to guys who know webpack and stuff - that will make your project much more difficult than careful reading the vanilla TS documentation.

**Comment by alamboley** [comment]
Thanks for the help @ivanpopelyshev. In the meantime would you mind to add me as a collaborator on pixi-haxe repository? Since Adi passed away PR aren't merged anymore etc. I don't want to see his hardwork failed too.

**Comment by ivanpopelyshev** [comment]
I told the team about it, someone will look into it.
