### ISSUE TITLE
namespace Extras isnt longer available 

### ISSUE THREAD

**Issue by kolezka** [pixijs/pixi-typescript#217]
"PIXI.extras" has been removed. All classes previous nested under this namespace have been moved to the top-level PIXI object.

**Comment by bigtimebuddy** [comment]
V5 typings are now available in the package. This repo is only for v4.

**Comment by ivanpopelyshev** [comment]
Yo, @kolezka ! To get v5 typings , type `npm install pixi.js` and take them from `node_modules/pixi.js/pixi.js.d.ts` . Or you can clone pixijs and build it, it 'll be in `bundles/pixi.js/pixi.js.d.ts`. We dont store that file in the repo anymore because its generated.

I will ask @bigtimebuddy to add this file into our CDN.

**Comment by bigtimebuddy** [comment]
You don’t need to download the file. Typescript will pull because it’s defined in the package.json types field.

**Comment by clark-stevenson** [comment]
@ivanpopelyshev @bigtimebuddy 

I have not used pixi for a while, but I got a quick play of V5 and you guys did an amazing job with the types!  I wasn't on it long, but I never got a single annoying type problem! 

Really well done!

As stated, something like `npm install pixi.js`  then using it in TypeScript as `import * as PIXI from "pixi.js"` was all I needed to do 👍 👍

**Comment by clark-stevenson** [comment]
Should I make a note of this fact in the readme here?

**Comment by clark-stevenson** [comment]
I did make a small note in the readme.  Cheers!
