### ISSUE TITLE
Typings install installs old type definitions

### ISSUE THREAD

**Issue by JustASquid** [pixijs/pixi-typescript#58]
I'm attempting to install these type definitions in my project using [typings](https://github.com/typings/typings/).

However `typings install dt~pixi.js --global` installs [this outdated type definition](https://github.com/retyped/pixi.js-tsd-ambient/blob/master/pixi.js.d.ts).

Is there anything we can do about this?

**Comment by clark-stevenson** [comment]
Thanks for letting me know :+1: 

I am really not sure how to solve this.

For me, I just pushed here and then some day, a dude did all the work to push it to DT (now typings).

However, I have no idea how to maintain it, as far as I understand, there is `pixijs/pixi-typescript` which is where the party is at, and then there is `definitelytyped/pixi-js/` version, which is essentially a clone.

Does anyone know if we can get rid of this relationship? Is it possible for Typings to understand that 

`dt-pixi.js` is actually `pixijs/pixi-typescript/pixi.d.ts` so go get that?

**Comment by staff0rd** [comment]
It looks like this issue has kind of been resolved considering typings now lists a DefinitelyTyped hosted declaration rather than the old Retyped one as above.  However, its obviously better that rather than these registries holding a copy of the file(s), instead the registry should point to the latest version of the file(s) in this repository.  Looking at [this](https://github.com/typings/typings/issues/322), the [Future of Declaration Files](https://blogs.msdn.microsoft.com/typescript/2016/06/15/the-future-of-declaration-files/) and the links on [Contributing as Package Author](https://github.com/typings/registry#as-package-author), I get the feeling that they're pushing for a best case scenario where typescript definitions are distributed directly from a project's main repo/npm package.

**Comment by clark-stevenson** [comment]
Really awesome post, and links. :+1:

**Comment by clark-stevenson** [comment]
I am still pretty baffled!  So `tsd` is gone because of `typings` but now that is also gone too kind of in favour of `npm` but only in TypeScript 2.0? 

Trying to wrap my head around all of it.  It seems this repo needs to die, and that each individual `/pixi/x` repo needs typings should the authors allow it as has been touched on here.   Which I could try to blackmail or bribe if required. 

But then there is a explosion of complexities which I currently do not understand, `pixi-spine.d.ts` for example would be `pixi.spine/typings/index.d.ts` but that does not work without a future `pixi.js/typings/index.d.ts`.   It all starts to get a bit murky.   

However, I am still checking this out when I have time just incase anyone is wondering

**Comment by bruce965** [comment]
Hope this is going to help somehow...

I believe the correct way to install type definitions for current repository configuration is the following:

```
typings install --save --global github:pixijs/pixi-typescript/pixi.js.d.ts#v4.1.0
```

The following more concise syntax doesn't seem to work at the moment because `typings.json` is missing in the repository. Not sure what this file should contain.

```
typings install --save --global github:pixijs/pixi-typescript#v4.1.0
```

**Comment by sommerper** [comment]
@bruce965 Thanks. The github link needs to be in quotes though. At least on macOS.

**Comment by ivanpopelyshev** [comment]
@sommerper you also can use typings from definitely-typed, but they are a bit outdated (~a month)

**Comment by clark-stevenson** [comment]
Hey guys, can I ditch `typings` now that we have `@types`?

Very soon if not already, we use TypeScript2 features. So you need a 2 version and therefor I will just say in the readme:

"Requires TypeScript 2.  Install from @types/pixi.js" 

Otherwise I am confused again where typings fits into the system when we are already on `dt`.

**Comment by Majirefy** [comment]
@clark-stevenson 
`@types`is Microsoft's new recommending way for Typescript definitions. But `@types/pixi.js` is always not the latest version of pixi.js.

I really appreciate the way MS changing for TypeScript definitions, because it makes npm as the only dependency of definition system.

To check out new `@types`, go to [Types](http://aka.ms/types). But there are some problems.
In pop-up list, it says pixi.js is version `3.0.9 dev`, but when page turns forward to npm site, it says version is 4.3.1.

But after `npm install --save @types/pixi.js`, when you open file '`index.d.ts`' in your project's `node_modules/@types/pixi.js/` directory, it says '`// Type definitions for Pixi.js v4.3.0`'.

I love TypeScript, how to help with it?

**Comment by ivanpopelyshev** [comment]
They have too much bureaucracy at DefinitelyTyped: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/14318

They cant just merge it, i have to add tslint and check all the boxes. I don't like it :(

**Comment by ivanpopelyshev** [comment]
And yeah, tslint failed. @clark-stevenson do something about it please? Introduce tslint to our repo. Their tslint failing our typings

**Comment by clark-stevenson** [comment]
I grabbed a `tslint.json` from somewhere on the DT core. 

I believe that refers to `../tslint.json` in your lint file so I have fixed a bunch of stuff, but there is 2 things that remain which I can't fix at the moment until later

1. `isMobile` has `any`, there is a property in pixi somewhere with "___plugins" as well.  These 2 things cause linting to fail.  I think we need to ditch those lints like this:

```
{
    "extends": "../tslint.json",
    "rules": {
        "variable-name": false
    }
}
```

2.  Someone a long time ago added this line to the bottom of the file. 

```
declare module "pixi.js" {
    export = PIXI
}
```

When this is changed to the following then it doesn't work.   I am not 100% sure what this means or how to deal with it, but it is TypeScript error as a result of fixing linting suggestions so currently it is a deal breaker. 

```
declare namespace "pixi.js" {
    export = PIXI;
}
```

I need to look for an alternative to that. 

Finally, one related question, is there any problems if I rename the file to `index.d.ts` so it is easy to drag and drop to DT repo? I will also delete the old examples, and rename the `v4` to that old one.

But I have no idea where `3.0.9 dev` is coming from.

**Comment by ivanpopelyshev** [comment]
rename - NO
tests - YES

**Comment by clark-stevenson** [comment]
I couldn't get the answer I was looking for on DT! I used the default `tslint --init` which generated a standard lint file which is now in the root. 

`npm install tslint -g`

Then `tslint pixi.js-tests.ts` and `tslint pixi.js.d.ts` 

I fixed all the problems that these files had.  

However, the dependency `isMobile` has a `any` property which breaks linting.  Since `any` is a type. So for that reason, your Definitely Typed lint should look like `dt/tslint.json`. 

So `tslint -c dt/tslint.json pixi.js-tests.ts` and `tslint -c dt/tslint.json pixi.js.d.ts`

Both pass. 

However, who knows what the REAL DT ruleset looks like.  But this should get us started for sure and slice away the majority of errors. 

Tests updated also.

**Comment by ryanlangton** [comment]
I cannot get the .d.ts files from this repository to work with VS code.  I use `@types/pixi.js` or any other library from @types and it works fine, but obviously getting old typings for pixi.  Just adding in a +1 for getting this fixed and working with @types.  Thanks.

**Comment by clark-stevenson** [comment]
Hey guys, so I never understood Typings, and its dead so that isn't going to happen I think.

On the bright side, I made a [PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/17099) to DT so `npm install @types/pixi.js` should do the job as soon as it is accepted and be up to date as of todays dev / 4.5

Hopefully this also resolves this stale issue.  Feel free to open should acquiring continue to be a problem (or you can help support older methods).
