### ISSUE TITLE
Tool Assistence

### ISSUE THREAD

**Issue by englercj** [pixijs/pixi-typescript#70]
I threw this together the other day, I wonder if there is a good way to use that here?

https://github.com/englercj/tsd-jsdoc

**Comment by clark-stevenson** [comment]
@englercj 

This is awesome! 

I am a bit of a novice here with the whole build and JSDoc stuff.  

https://github.com/pixijs/pixi.js/blob/dev/gulp/util/jsdoc.conf.json

Assuming that I have `tsd-jsdoc` in my `node_modules`, is there anything else that should be changed apart from the `template` in the above?

Just trying to hack something together.  I would love to get this working.

**Comment by englercj** [comment]
Nope, just changing the template to point to the tsd-jsdoc directory should do it. or running the CLI with `-t` flag.

**Comment by clark-stevenson** [comment]
There was discussion somewhere about this but this was a long time ago.  I did get the point others made that, there is a lot of "added" shape which only a human could add.  Most interfaces exist just to fill in holes which would otherwise not exist, or be `any`.  

But now with ES6, I wonder if it is worth taking a look at this again or if the same issues are still under the hood.

**Comment by englercj** [comment]
Just released the beta version of v2 of tsd-jsdoc: https://github.com/englercj/tsd-jsdoc

A much more robust implementation of converting jsdoc -> dts files.

**Comment by clark-stevenson** [comment]
I am going to close this because I failed multiple times to get it working over the months.

But it isn't just that. I still haven't seen evidence that it is possible to do what is needed given the size of the file.  For example 3 Humans were needed recently to implement an Interface which could satisfy Point | Observable point.

That can never be done by a tool, and over the years, and especially.... when thinking of dependencies (Consider the stuff in here that doesn't belong.... Your loader etc).   Each generation of the library, no matter how good the implementation and docs......

It isn't going to shine a light to TypeScript's superset of ideas.  So trying to generate it when the information just isn't there.... it will create more problems that it is worth.  Especially since I moved out of Pixi at the start of the year and feel a bit of a charlatan making releases my ass can't cash.  

👍
